### ISSUE TITLE
python3 install error from pypi

### ISSUE THREAD

**Issue by sckott** [sckott/habanero#25]
```
~$ pip3 install habanero 

Collecting habanero
  Downloading habanero-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/gs/4khph0xs0436gmd2gdnwsg080000gn/T/pip-build-cjtn36i_/habanero/setup.py", line 8, in <module>
        with codecs.open('Changelog.rst', 'r', 'utf-8') as f:
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/codecs.py", line 891, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: 'Changelog.rst'
```

weird that it errors on a changelog file not found, but I must have done something wrong there. 

note: `pip install habanero` works fine for python2

**Comment by sckott** [comment]
this should be sorted now

using a universal wheel build now, when calling `sdist`

will deploy new patch version to pypi today, i think
