### ISSUE TITLE
search for Title fails with KeyError: 'content-type'

### ISSUE THREAD

**Issue by a59** [sckott/habanero#53]
```
import habanero
cr = habanero.Crossref()
print 'Title 1:'
title = 'On the use of fittin'
x = cr.works(query_title = title)
print len(x['message']['items'])
print 'Title 2:'
title = 'On the use of fitting'
x = cr.works(query_title = title)
print len(x['message']['items'])
```

The search for Title 1 works but the search for Title 2 fails with KeyError: 'content-type'

**Comment by sckott** [comment]
@a59 what version of `habanero` do you have?  i can't replicate your issue

**Comment by a59** [comment]
I am running Version: 0.2.6.

This is what I got when I ran the script just now

```
Title 1:
Traceback (most recent call last):
  File "test001.py", line 5, in <module>
    x = cr.works(query_title = title)
  File "/usr/local/lib/python2.7/site-packages/habanero/crossref/crossref.py", line 162, in works
    order, facet, cursor, cursor_max, **kwargs).do_request()
  File "/usr/local/lib/python2.7/site-packages/habanero/request_class.py", line 54, in do_request
    js = self._req(payload = payload)
  File "/usr/local/lib/python2.7/site-packages/habanero/request_class.py", line 80, in _req
    if is_json(r):
  File "/usr/local/lib/python2.7/site-packages/habanero/habanero_utils.py", line 43, in is_json
    if re.search('json', x.headers['Content-Type']).__class__.__name__ == 'NoneType':
  File "/usr/local/lib/python2.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-type'
```
Running with the debugger I got

```
-> import habanero
(Pdb) cont
Title 1:
20
Title 2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "test001.py", line 1, in <module>
    import habanero
  File "/usr/local/lib/python2.7/site-packages/habanero/crossref/crossref.py", line 162, in works
    order, facet, cursor, cursor_max, **kwargs).do_request()
  File "/usr/local/lib/python2.7/site-packages/habanero/request_class.py", line 54, in do_request
    js = self._req(payload = payload)
  File "/usr/local/lib/python2.7/site-packages/habanero/request_class.py", line 80, in _req
    if is_json(r):
  File "/usr/local/lib/python2.7/site-packages/habanero/habanero_utils.py", line 43, in is_json
    if re.search('json', x.headers['Content-Type']).__class__.__name__ == 'NoneType':
  File "/usr/local/lib/python2.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-type'
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /usr/local/lib/python2.7/site-packages/requests/structures.py(54)__getitem__()
-> return self._store[key.lower()][1]
(Pdb) doc()
*** NameError: name 'doc' is not defined
(Pdb) dir()
['key', 'self']
(Pdb) key
'Content-Type'
(Pdb) up
> /usr/local/lib/python2.7/site-packages/habanero/habanero_utils.py(43)is_json()
-> if re.search('json', x.headers['Content-Type']).__class__.__name__ == 'NoneType':
(Pdb) dir()
['x']
(Pdb) x
<Response [500]>
(Pdb) 
```

I wonder if it is something to do with the CrossRef API metering the number of queries. I have done a lot of queries today as I am trying to sort out a pile of pdfs.

**Comment by a59** [comment]
I tried again this morning and confirmed that it is an intermittent fault. It sometimes works and sometimes does not.

**Comment by sckott** [comment]
there is rate limiting, see https://github.com/CrossRef/rest-api-doc/blob/master/rest_api.md#rate-limits and we've documented in the library as well. 

you can use verbose http output, see https://github.com/sckott/habanero/blob/master/habanero/__init__.py#L29-L41 for how to do that with `habanero`

**Comment by sckott** [comment]
Did you try verbose http output?  Curious if that gave you any clarity?

**Comment by a59** [comment]
I added the code for verbose output and this is what I got back.

```
Title 1:
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.crossref.org
send: 'GET /works?query.title=On+the+use+of+fittin HTTP/1.1\r\nHost: api.crossref.org\r\nConnection: keep-alive\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nUser-Agent: python-requests/2.13.0 habanero/0.2.6\r\nX-USER-AGENT: python-requests/2.13.0 habanero/0.2.6\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type: application/json;charset=UTF-8
header: Vary: Accept
header: Access-Control-Allow-Origin: *
header: Access-Control-Allow-Headers: X-Requested-With
header: Content-Length: 199004
header: Server: http-kit
header: Date: Mon, 24 Apr 2017 20:17:03 GMT
header: X-Rate-Limit-Limit: 50
header: X-Rate-Limit-Interval: 1s
header: Connection: close
DEBUG:requests.packages.urllib3.connectionpool:http://api.crossref.org:80 "GET /works?query.title=On+the+use+of+fittin HTTP/1.1" 200 199004
20
Title 2:
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.crossref.org
send: 'GET /works?query.title=On+the+use+of+fitting HTTP/1.1\r\nHost: api.crossref.org\r\nConnection: keep-alive\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nUser-Agent: python-requests/2.13.0 habanero/0.2.6\r\nX-USER-AGENT: python-requests/2.13.0 habanero/0.2.6\r\n\r\n'
reply: 'HTTP/1.1 500 Internal Server Error\r\n'
header: Exception-Name: class java.lang.RuntimeException
header: Content-Length: 264
header: Server: http-kit
header: Date: Mon, 24 Apr 2017 20:17:20 GMT
header: X-Rate-Limit-Limit: 50
header: X-Rate-Limit-Interval: 1s
header: Connection: close
DEBUG:requests.packages.urllib3.connectionpool:http://api.crossref.org:80 "GET /works?query.title=On+the+use+of+fitting HTTP/1.1" 500 264
Traceback (most recent call last):
  File "test001.py", line 24, in <module>
    x = cr.works(query_title = title)
  File "/usr/local/lib/python2.7/site-packages/habanero/crossref/crossref.py", line 162, in works
    order, facet, cursor, cursor_max, **kwargs).do_request()
  File "/usr/local/lib/python2.7/site-packages/habanero/request_class.py", line 54, in do_request
    js = self._req(payload = payload)
  File "/usr/local/lib/python2.7/site-packages/habanero/request_class.py", line 80, in _req
    if is_json(r):
  File "/usr/local/lib/python2.7/site-packages/habanero/habanero_utils.py", line 43, in is_json
    if re.search('json', x.headers['Content-Type']).__class__.__name__ == 'NoneType':
  File "/usr/local/lib/python2.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-type'
```

**Comment by sckott** [comment]
Interesting, for the 2nd one that fails, i'm getting:


```
In [8]: print 'Title 2:'
          title = 'On the use of fitting'
          x = cr.works(query_title = title)

DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.crossref.org
send: 'GET /works?query.title=On+the+use+of+fitting HTTP/1.1\r\nHost: api.crossref.org\r\nConnection: keep-alive\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nUser-Agent: python-requests/2.13.0 habanero/0.2.6.3\r\nX-USER-AGENT: python-requests/2.13.0 habanero/0.2.6.3\r\n\r\n'
reply: 'HTTP/1.1 500 Internal Server Error\r\n'
header: Exception-Name: class java.lang.RuntimeException
header: Content-Length: 264
header: Server: http-kit
header: Date: Tue, 25 Apr 2017 02:51:38 GMT
header: X-Rate-Limit-Limit: 50
header: X-Rate-Limit-Interval: 1s
header: Connection: close
DEBUG:requests.packages.urllib3.connectionpool:http://api.crossref.org:80 "GET /works?query.title=On+the+use+of+fitting HTTP/1.1" 500 264
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-8-ff9de95f204e> in <module>()
      1 print 'Title 2:'
      2 title = 'On the use of fitting'
----> 3 x = cr.works(query_title = title)

/Users/sacmac/github/sac/habanero/habanero/crossref/crossref.pyc in works(self, ids, query, filter, offset, limit, sample, sort, order, facet, cursor, cursor_max, **kwargs)
    181             return Request(self.base_url, "/works/",
    182               query, filter, offset, limit, sample, sort,
--> 183               order, facet, cursor, cursor_max, None, **kwargs).do_request()
    184
    185     def members(self, ids = None, query = None, filter = None, offset = None,

/Users/sacmac/github/sac/habanero/habanero/request_class.pyc in do_request(self)
     52     payload = rename_query_filters(payload)
     53
---> 54     js = self._req(payload = payload)
     55     cu = js['message'].get('next-cursor')
     56     max_avail = js['message']['total-results']

/Users/sacmac/github/sac/habanero/habanero/request_class.pyc in _req(self, payload)
     82         raise RequestError(r.status_code, f['message'][0]['message'])
     83       except:
---> 84         r.raise_for_status()
     85     except requests.exceptions.RequestException as e:
     86       print(e)

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/models.pyc in raise_for_status(self)
    907
    908         if http_error_msg:
--> 909             raise HTTPError(http_error_msg, response=self)
    910
    911     def close(self):

HTTPError: 500 Server Error: Internal Server Error for url: http://api.crossref.org/works?query.title=On+the+use+of+fitting
```

Can you upgrade to the dev version https://github.com/sckott/habanero#installation and see if at least you're getting the same error as me. 

The problem with the query that doesn't work is a Crossref issue - related questions to this issue have been asked over at https://github.com/CrossRef/rest-api-doc/issues (including me https://github.com/CrossRef/rest-api-doc/issues/171) - but it's unlikely to be dealt with any time soon (i'm not sure why but they haven't been responding to any issues at all in the recent past)

**Comment by sckott** [comment]
By the way, the query that works I have received the same error response on sometimes, so I don't think it's jus the difference of the two query terms (but rather a failure on their servers unrelated to the query terms given)

**Comment by a59** [comment]
I did upgrade to the development version and did get the same error. Although it's a problem with the CrossRef api, may I put in a request that habanero fail gracefully, somehow?

**Comment by sckott** [comment]
> may I put in a request that habanero fail gracefully, somehow?

What do you imagine is more graceful?

**Comment by a59** [comment]
I am searching a long list of paper titles to match them to pdfs in my library. Raising an exception is fine, but maybe issuing a warning that nothing could be found would be more useful.

**Comment by sckott** [comment]
thanks for that. 

I think what currently happens is the appropriate response.   What you can easily do though is use e.g, 

```python
try:
  z = cr.works(query_title = title, limit="adf")
except:
  z = None
```

so that you can loop/map over many things and failures give back whatever you like (e.g., `None`)

**Comment by sckott** [comment]
any thoughts @a59 ?

**Comment by sckott** [comment]
Don't seem to be seeing this error anymore, closing, we can reopen if this keeps happening

**Comment by nastyatrvl** [comment]
I get the same error but with a different key ('total-results'). So the problem still exists.

**Comment by sckott** [comment]
@nastyatrvl please provide a reproducible example

**Comment by nastyatrvl** [comment]
```time python3 all_code/get_pubs_crossref.py    # to get potentially related works filtering by authors (RCT's PI) and publication dates (after RCT's start date using the Crossref API).
Traceback (most recent call last):
  File "/lustre2/home/as2764/workdir/rct-matching-text-1/all_code/get_pubs_crossref.py", line 124, in <module>
    main()
  File "/lustre2/home/as2764/workdir/rct-matching-text-1/all_code/get_pubs_crossref.py", line 115, in main
    cr_pubs = get_pub_info(exp_data)
  File "/lustre2/home/as2764/workdir/rct-matching-text-1/all_code/get_pubs_crossref.py", line 100, in get_pub_info
    res = cr.works(query = "economics", query_author = pi, filter = {'from_pub_date': row['Start date']}, progress_bar=True)
  File "/lustre2/home/as2764/workdir/rct-matching-text-1/env/lib64/python3.9/site-packages/habanero/crossref/crossref.py", line 368, in works
    return Request(
  File "/lustre2/home/as2764/workdir/rct-matching-text-1/env/lib64/python3.9/site-packages/habanero/request_class.py", line 108, in do_request
    max_avail = js["message"]["total-results"]
KeyError: 'total-results'```

**Comment by nastyatrvl** [comment]
https://github.com/fabiobatalha/crossrefapi/blob/master/crossref/restful.py#L250

**Comment by sckott** [comment]
thanks but that's not a reproducible example

**Comment by nastyatrvl** [comment]
What would be a reproducible one?

**Comment by sckott** [comment]
Sorry for the very late reply! A reproducible example means one that anyone can run - and ideally it's very brief
