### ISSUE TITLE
registration_agency example doesn't work. 

### ISSUE THREAD

**Issue by AlexHenderson** [sckott/habanero#72]
... or am I doing something wrong :-/

Thanks, Alex

```python
Python 3.6.4 |Anaconda, Inc.| (default, Mar 12 2018, 20:20:50) [MSC v.1900 64 bit (AMD64)] on win32
>>> from habanero import Crossref
>>> cr = Crossref()
>>> cr.registration_agency('10.1371/journal.pone.0033693')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "{anon}\lib\site-packages\habanero\crossref\crossref.py", line 683, in registration_agency
    None, None, None, None, None, True, **kwargs)
  File "{anon}\lib\site-packages\habanero\request.py", line 19, in request
    raise ValueError("cursor_max must be of class int")
ValueError: cursor_max must be of class int
>>>
```

**Comment by sckott** [comment]
woopsy, thanks for reporting it, will fix

**Comment by sckott** [comment]
@AlexHenderson fixed, try again after reinstalling from github

**Comment by AlexHenderson** [comment]
All good now. Thanks for the quick turnaround.
